# Change these first
owner: factiverse # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: POST to /stance_detection
    url: https://api.factiverse.ai/v1/stance_detection
    method: POST
    headers:
      - "Authorization: Bearer $API_KEY"
      - "accept: application/json"
      - "Content-Type: application/json"
    body: >-
      {
        "claim": "The earth is flat.",
        "logging": false,
        "lang": "en",
        "search_engines": [
          "Bing Search",
          "Google",
          "Google Claim",
          "Semantic Scholar",
          "Wikipedia",
          "ElasticSearch",
          "You.com"
        ],
        "preferred_sites": [
          "ft.com",
          "bbc.com",
          "wsj.com",
          "cbsnews.com",
          "channel4.com/news",
          "channelnewsasia.com"
        ]
      }
    maxResponseTime: 100000
    assignees:
      - tobiastykvart
      - vinaysetty
      - bohdan-meshcheriakov-factiverse
  - name: POST to /claim_detection
    url: https://api.factiverse.ai/v1/claim_detection
    method: POST
    headers:
      - "Authorization: Bearer $API_KEY"
      - "accept: application/json"
      - "Content-Type: application/json"
    body: >-
      {
        "lang": "",
        "logging": false,
        "text": "I think we've seen a deterioration of values. US has the highest number of COVID infections ever.",
        "claimScoreThreshold": 0.9
      }
    maxResponseTime: 100000
    assignees:
      - tobiastykvart
      - vinaysetty
      - bohdan-meshcheriakov-factiverse
  - name: POST to /fact_check
    url: https://api.factiverse.ai/v1/fact_check
    method: POST
    headers:
      - "Authorization: Bearer $API_KEY"
      - "accept: application/json"
      - "Content-Type: application/json"
    body: >-
      {
        "logging": false,
        "lang": "",
        "collection": "test",
        "claims": [
          "The earth is flat."
        ],
        "url": "https://www.bbc.com/news/world-asia-58112981",
        "text": "The director of Afghanistan's media and informationcentre has been assassinated by Taliban militants inthe capital, Kabul. Dawa Khan Menapal was killed bygunmen on Darul Aman Road in the capital, reports said. I am not worth checking.",
        "domainsToSearch": [
          "news",
          "encyclopedia",
          "research",
          "social_media"
        ]
      }
    maxResponseTime: 200000
  - name: POST to /search
    url: https://api.factiverse.ai/v1/search
    method: POST
    headers:
      - "Authorization: Bearer $API_KEY"
      - "accept: application/json"
      - "Content-Type: application/json"
    body: >-
      {
        "claim": "The earth is flat.",
        "lang": "en",
        "logging": false,
        "search_engines": [
          "Bing Search",
          "Google",
          "Google Claim",
          "Semantic Scholar",
          "Wikipedia",
          "ElasticSearch",
          "You.com"
        ],
        "preferred_sites": [
          "ft.com",
          "bbc.com",
          "wsj.com",
          "cbsnews.com",
          "channel4.com/news",
          "channelnewsasia.com"
        ]
      }
    maxResponseTime: 100000
  - name: POST to /feedback
    url: https://api.factiverse.ai/v1/feedback
    method: POST
    headers:
      - "Authorization: Bearer $API_KEY"
      - "accept: application/json"
      - "Content-Type: application/json"
    body: >-
      {
        "feedbackType": "UITest",
        "logging": false,
        "payload": {
          "claim": "Global warming is caused by greenhouse ...",
          "email": "email@example.no",
          "userAgrees": true,
          "lang": "en",
          "evidence": {
            "title": "Greenhouse gas emissions by Australia",
            "url": "https://en.wikipedia.org/?curid=20802345",
            "domain": "https://en.wikipedia.org/",
            "snippet": "Greenhouse gas emissions by Australia ...",
            "softmaxScore": [
              0.1234,
              0.4321
            ],
            "id": "a1483395-7765-4ea5-9fe3-1qqdd23a147c"
          }
        }
      }
    maxResponseTime: 100000
  - name: POST to /claim_search
    url: https://api.factiverse.ai/v1/claim_search
    method: POST
    headers:
      - "Authorization: Bearer $API_KEY"
      - "accept: application/json"
      - "Content-Type: application/json"
    body: >-
      {
        "logging": false,
        "lang": "",
        "query": "The earth is not flat.",
        "fromDate": "2023-12-01",
        "toDate": "2024-01-01",
        "reverseSortPubDate": true,
        "size": 10,
        "searchEngine": [
          "fact_search_elasticsearch"
        ]
      }
    maxResponseTime: 100000
  - name: POST to /generate
    url: https://api.factiverse.ai/v1/generate
    method: POST
    headers:
      - "Authorization: Bearer $API_KEY"
      - "accept: application/json"
      - "Content-Type: application/json"
    body: >-
      {
        "logging": false,
        "lang": "",
        "text": "Are you an AI?",
        "prompt": "Are you an AI?"
      }
    maxResponseTime: 100000
    assignees:
      - bohdan-meshcheriakov-factiverse
      - vinaysetty
  - name: DNB Pilot (azure.factiverse.ai)
    url: https://azure.factiverse.ai/v1/docs
    assignees:
      - tobiastykvart
      - vinaysetty
      - bohdan-meshcheriakov-factiverse
  - name: Ollama
    url: https://ollama.factiverse.ai
    assignees:
      - bohdan-meshcheriakov-factiverse
      - vinaysetty
  - name: Factisearch
    check: "tcp-ping"
    url: es.factiverse.ai
    port: 9200
    assignees:
      - eemrds
      - vinaysetty

workflowSchedule:
  uptime: "*/10 * * * *"           # This is the most important one — run checks every 10 mins
  responseTime: "*/10 * * * *"     # API response time
  updates: "*/30 * * * *"          # Update other metadata less frequently
  summary: "0 * * * *"             
  graphs: "0 * * * *"              
  staticSite: "0 0 * * *"          
  updateTemplate: "0 0 * * 0"      

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://avatars.githubusercontent.com/u/60502496?s=200&v=4
  name: Factiverse Systems Status
  introTitle: "**Factiverse** Systems Status**"
  introMessage: This site monitors if our systems are up and running as intended.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
