# Change these first
owner: factiverse # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Prod API (api.factiverse.ai)
    check: "tcp-ping"
    url: api.factiverse.ai
    assignees:
      - tobiastykvart
      - vinaysetty
  - name: DNB Pilot (azure.factiverse.ai)
    url: https://azure.factiverse.ai/v1/docs
    assignees:
      - tobiastykvart
      - vinaysetty
  - name: Ollama
    url: https://ollama.factiverse.ai
    assignees:
      - vinaysetty
    
workflowSchedule:
  graphs: "*/1 * * * *"
  responseTime: "*/1 * * * *"
  staticSite: "*/1 * * * *"
  summary: "*/1 * * * *"
  updateTemplate: "*/1 * * * *"
  updates: "*/1 * * * *"
  uptime: "*/1 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://avatars.githubusercontent.com/u/60502496?s=200&v=4
  name: Factiverse Systems Status
  introTitle: "**Factiverse** Systems Status**"
  introMessage: This site monitors if our systems are up and running as intended.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
